.github/pull_request_template.md

updating the PR template to have a callout to frontend PRs as requested by Michelle

add design instructions to PR template

---

query-connector/src/app/format-service.tsx
query-connector/src/app/query/components/backLink/Backlink.tsx
query-connector/src/app/query/components/customizeQuery/CustomizeQueryAccordionBody.tsx
query-connector/src/app/query/components/resultsView/tableComponents/Demographics.tsx
query-connector/src/app/query/components/resultsView/tableComponents/EncounterTable.tsx
query-connector/src/app/query/stepIndicator/StepIndicator.tsx

had a slew of frontend errors that crept up in recent weeks that I went ahead and fixed since I had time

fix frontend errors

---

query-connector/e2e/alternate_queries.spec.ts
query-connector/src/app/constants.ts

Comments out social determinants as a dropdown select until we can pick up work in future ticket (#61).
Fixes #52 
For frontend PR’s - include a description (including anything that’s out of scope) for what you want the designers to review
- ex: _“Check out the whitespace on the page, as well as the dropdowns in the form. Here is the corresponding Figma link. You can ignore everything else. Also, the button at the bottom doesn’t work now”_

Removing social determinants of health from select query dropdown

---

query-connector/src/app/query/components/footer/footer.module.scss
query-connector/src/app/query/components/header/header.module.scss
query-connector/src/app/query/components/header/header.tsx
query-connector/src/app/signin/page.tsx
query-connector/src/app/signin/signinPage.module.scss
query-connector/src/styles/_variables.scss
query-connector/src/styles/custom-styles.scss

sets the sign in page content to fill up the whole width between the header / footer since I pulled out the grid styling on the main container that made it work before 😅 .

fix sign in page height

---

.github/workflows/target_workflow.yaml

- Add missing `"` to target_workflow.yaml
It caused the following error message during deployment

Fix Workflow syntax

---

query-connector/src/app/queryBuilding/queryBuilding.module.scss

fix for the border hover state issue on the my queries page

style border using after psuedo element

---

query-connector/src/app/query/components/CustomizeQuery.tsx
query-connector/src/app/query/designSystem/redirectToast/RedirectToast.tsx
query-connector/src/app/queryBuilding/dataState/UserQueriesDisplay.tsx
query-connector/src/app/queryBuilding/dataState/utils.tsx

tweak the toast rendering and icon alignment on the queries page

tweak toast and icon alignment

---

query-connector/src/app/database-service.ts
query-connector/src/app/queryBuilding/dataState/UserQueriesDisplay.tsx

Changes and simplifies some of the frontend and backend work for My Queries based off update to `query` table by @fzhao99 .
Fixes #
@fzhao99 , I noticed a few smaller places we can simplify with the `query` table work that didn't block your PR. I can also stand up post your PR merging, but I wanted to do this while the work was still fresh in mind.

Small updates to My Query page with update to query table

---

query-connector/src/app/queryBuilding/buildFromTemplates/BuildFromTemplates.tsx
query-connector/src/app/queryBuilding/components/SelectionTable.tsx
query-connector/src/app/queryBuilding/components/SelectionViewAccordionBody.tsx

What changes are being proposed? For PRs that include UX/UI changes please make sure to describe their scope and highlight any specific areas that design reviews should focus.
Fixes #

Resolving npm run build errors

---

query-connector/src/app/query/components/header/header.tsx

adding `fhir servers` to the list of paths that show up in the gear dropdown

add fhir-servers to the list of logged in paths

---

query-connector/flyway/sql/V05_01__add_user_management.sql

Adds the user management table with a few pieces of info, which we'll then pull from Keycloak. 
Looks like we shouldn't have any issues with the metadata, as it's all here: https://wjw465150.gitbooks.io/keycloak-documentation/content/server_admin/topics/users/create-user.html (username, first/last name) in preparation for the next ticket up: https://linear.app/skylight-cdc/issue/QUE-126/update-authts-to-return-user-info-for-storage-from-keycloak.
Fixes #270 

Initializing user management table

---

query-connector/e2e/query_building.spec.ts
query-connector/src/app/queryBuilding/components/SelectionViewAccordionBody.tsx

Some straggler tests to cover toggling of individual concept codes

e2e test editing value sets and concept codes

---

query-connector/src/app/(pages)/queryBuilding/components/SelectionTable.tsx
query-connector/src/app/ui/designSystem/drawer/Drawer.tsx
query-connector/src/app/ui/designSystem/searchField/SearchField.tsx

Fixes the bug introduced in [this PR](https://github.com/CDCgov/dibbs-query-connector/pull/309) as detailed [here](https://skylight-hq.slack.com/archives/C05BEG226RZ/p1738184273394609)
Is a little late in the day for me so wanted to get the cut of main working first, but will add a test in to catch future instances of this issue first thing tomorrow
https://github.com/user-attachments/assets/a9a8ac57-25a2-45dd-bd59-9731c408f734

fix state initialization problems

---

query-connector/Dockerfile
query-connector/src/app/backend/dbCreation/db-creation.ts
query-connector/src/app/shared/database-service.ts

Ran into a minor issue, detailed [here](https://skylight-hq.slack.com/archives/C05BEG226RZ/p1738259663759969) where a clean build was failing. I think is just an artifact of the recent rework of our folder structure, but i guess two things to confirm when testing:
1. did you encounter the same error after pruning existing volumes on main?
2. does this fix work for you?
Fixes #

DB Creation fix

---

terraform/implementation/ecs/main.tf

This PR will change the default ALB's listener rule condition to root for the query-connector service /* and /
and allows developer's to customize the rule condition for services such as keycloak. 
- Can modify the listerner rules' priority based on application configs
Fixes #

ALB update

---

query-connector/src/app/ui/components/header/header.tsx

Changes the redirect of the main QC logo when logged in. Also added a redirect to log out while I was at it
Fixes #303

change redirect "homepage" click when logged in

---

query-connector/src/app/backend/dbServices/fhir-servers.ts

What changes are being proposed? For PRs that include UX/UI changes please make sure to describe their scope and highlight any specific areas that design reviews should focus.
Fixes #

make FHIR servers service class static

---

query-connector/src/app/shared/constants.ts

reverting a few hotfix additions to play nice with the new seed scripts

revert hotfix workarounds

---

query-connector/README.md

Add an extra note to our readme for the aidbox license needed to get the seeder to run

add extra note for local e2e

---

query-connector/src/app/(pages)/queryBuilding/buildFromTemplates/conditionTemplateSelection.module.scss
query-connector/src/app/(pages)/userManagement/components/managementTabs/__snapshots__/managementTabs.test.tsx.snap
query-connector/src/app/ui/designSystem/drawer/Drawer.tsx
query-connector/src/app/ui/designSystem/drawer/drawer.module.scss
query-connector/src/app/ui/designSystem/table/table.module.scss

Noticed some drawer styling issues during a demo and so went ahead and fixed it.
(setting the hard width via rem was creating the overlapping div and generally causing zooming issues) 
https://github.com/user-attachments/assets/a90cc64a-b06e-45b0-9e69-772c0337b341
https://github.com/user-attachments/assets/ed76f609-2222-4324-88fc-ef4c8c364078

drawer style tweaks

---

query-connector/src/app/(pages)/queryBuilding/querySelection/QuerySelection.tsx

What changes are being proposed? For PRs that include UX/UI changes please make sure to describe their scope and highlight any specific areas that design reviews should focus.
Fixes #437 

Alphabetize queries in the Query Library

---

query-connector/src/app/shared/page-routes.ts
query-connector/src/app/ui/components/header/header.tsx

Run query to `Run a query`
Fixes #516 

Updating Run a query button text

---

query-connector/src/app/shared/query-service.ts

Quick bug fix for the IZ Gateway.

Fix how includeImmunizations is read in patientRecordsQuery

---

query-connector/src/app/(pages)/landingPage/landingPage.tsx

Redirect to /query if logged in
Fixes #517
https://linear.app/skylight-cdc/issue/QUE-242/route-the-user-to-the-patient-information-page-ie-first-page-of

Redirect to /query if logged in

---

.github/workflows/cd.yaml

This PR will remove the troubleshooting code I added and restore the ability to push packages to the Container registry.
Fixes #

Quick fix Package release

---

.github/workflows/cd.yaml
.github/workflows/keycloak.yaml

Followup to #560 - didn't catch these because global search for some reason doesn't work in the `.github` directory 🤔

Followup - fix context in cd workflows

---

e2e/query_building.spec.ts
src/app/(pages)/queryBuilding/buildFromTemplates/conditionTemplateSelection.module.scss
src/app/(pages)/queryBuilding/components/SelectionViewAccordionBody.tsx
src/app/ui/styles/_variables.scss

Some focus state fixes based on the convo [here](https://skylight-hq.slack.com/archives/C05BEG226RZ/p1745511066162769)

query building focus state change on hover

---

e2e/query_editing.spec.ts
src/app/(pages)/queryBuilding/buildFromTemplates/BuildFromTemplates.test.tsx
src/app/(pages)/queryBuilding/buildFromTemplates/conditionTemplateSelection.module.scss
src/app/(pages)/queryBuilding/components/ConditionSelection.tsx
src/app/(pages)/queryBuilding/components/SelectionTable.tsx
src/app/(pages)/queryBuilding/components/ValueSetSelection.tsx
src/app/(pages)/queryBuilding/querySelection/QueryLibrary.tsx
src/app/(pages)/queryBuilding/utils.ts
src/app/shared/constants.ts

This adds codes to set up frontend support for custom codes. For now, the workflow to test:
1. Navigate to /queryBuilding.
2. Hit Create query.
3. Name the query `custom code test` (or whatever you like, you'll just need to update the `UPDATE` query below).
4. Click on whatever query you want; we'll be hard-updating it in the DB anway.
5. Save query.
6. Run the below `UPDATE`. It sets every query name to a dummy cancer condition that has the same cancer conditions set as a custom value set.
7. Refresh and navigate back to the `custom code test` to review.
Fixes #591 , #580
If this setup makes sense, I can create a follow up ticket to update tests.
We will also need to update the onClick behavior for the empty state go to code library and the add from library button when there are existing …

Updating /queryBuilding page to support Custom ValueSets

---

src/auth.ts

One last auth env var change to fix the issuer in our deployed dev env.

One more auth env var change

---

docs/deployment.md

Made some stylistic changes to the deployment guidelines - lmk if you have questions/want to discuss!
This PR covers proposed stylistic changes (mostly capitalization/punctuation related) -- no major UI/UX changes recommended! 
Fixes # (N/A)
Nothing else to note here!

Copy changes - deployment.md

---

src/app/(pages)/auditLogs/components/auditLogMaps.ts

Fixing a null pointer Dan pointed out [here](https://skylight-hq.slack.com/archives/C05BEG226RZ/p1748449284560689)
A little hard to debug here since we're dealing with environment mismatch issues but based on this console log, think this is the source of the error. Will verify this fixes it once it deploys

fix audit log null pointer

---

keycloak/demo.json
keycloak/dev.json
keycloak/localhost.json

Reverting the dev Keycloak seeding files to unbreak our redirects 
Put a reversion up to the state of things before the broken commit in [this branch](https://github.com/CDCgov/dibbs-query-connector/tree/bob/keycloak-original), but GitHub seems to be having trouble generating the diff. You can look at the difference between this version and the files prior to the breaking commit [here](https://www.diffchecker.com/nRrrZl0T/)

revert dev Keycloak

---

src/app/(pages)/queryBuilding/buildFromTemplates/__snapshots__/BuildFromTemplates.test.tsx.snap
src/app/(pages)/queryBuilding/buildFromTemplates/conditionTemplateSelection.module.scss
src/app/(pages)/queryBuilding/components/ValueSetSelection.tsx
src/app/tests/integration/audit-log/query-building.test.ts

Does a few frontend fixes to display the additional medical record section: https://skylight-hq.slack.com/archives/C07PQ078KK2/p1749137341601139?thread_ts=1748547838.437739&cid=C07PQ078KK2
also just fixes the tests. next branch will focus on adding more tests.
Fixes #655, partially
Since we are on code freeze and have some pretty meaty questions in the main branch re: the way to organize medical record sections in the backend, figured I'd at least knock out the frontend part in the meantime.

Frontend updates to add Medical Record Sections

---

src/app/ui/styles/custom-styles.scss

Realized we removed the toast styles when we updated the design system styles, so adding them back in.

add toast styles back in

---

src/app/(pages)/queryBuilding/buildFromTemplates/BuildFromTemplates.test.tsx
src/app/(pages)/queryBuilding/buildFromTemplates/__snapshots__/BuildFromTemplates.test.tsx.snap
src/app/(pages)/queryBuilding/buildFromTemplates/conditionTemplateSelection.module.scss
src/app/ui/designSystem/CustomAccordion.tsx
src/app/ui/styles/custom-styles.scss

Previous PR didn't include `fieldset` for the added `legend` tag; this adds that in and updates styling accordingly
Fixes #694 

Adjust styling for query building accordions

---

setup-scripts/e2e_tests_local.sh
src/app/(pages)/codeLibrary/CodeLibrary.test.tsx
src/app/(pages)/codeLibrary/components/CustomValueSetForm.test.tsx
src/app/(pages)/queryBuilding/buildFromTemplates/BuildFromTemplates.test.tsx
src/app/(pages)/queryBuilding/buildFromTemplates/__snapshots__/BuildFromTemplates.test.tsx.snap
src/app/(pages)/queryBuilding/page.test.tsx
src/app/(pages)/userManagement/components/teamQueryEditSection/__snapshots__/TeamQueryEditSection.test.tsx.snap
src/app/(pages)/userManagement/components/userManagementContainer/__snapshots__/userManagementContainer.test.tsx.snap
src/app/ui/designSystem/drawer/Drawer.tsx
src/app/ui/styles/custom-styles.scss

Adds a focus trap to the drawer component and some other QOL improvements during the tab accessibility effort. Breaking this out to unblock the work on the other pages that needs this component

add drawer focus trap

---

db-data/Conditions_and_Categories_20250707.csv
src/app/assets/dibbs_db_seed_category.json
src/app/tests/assets/aphlCategoryMapping.json

Quick update to seeding script so CA can get all categories.
Fixes #

Updating categories for latest eRSD Update

---

docker-compose-dev.yaml
src/app/(pages)/codeLibrary/page.tsx
src/app/(pages)/query/components/ResultsView.tsx
src/app/(pages)/query/components/resultsView/tableComponents/ServiceRequestTable.tsx
src/app/(pages)/queryBuilding/components/__snapshots__/ValueSetSelection.test.tsx.snap
src/app/(pages)/queryBuilding/fixtures.ts
src/app/(pages)/queryBuilding/utils.ts
src/app/backend/fhir-servers/fhir-client.ts
src/app/backend/query-execution/custom-query.ts
src/app/backend/query-execution/service.ts

Add in support for service requests as part of the Connectathon work

add in support for service requests
