containers/tefca-viewer/src/app/fhir-servers.ts

The eHealth Exchange FHIR proxy currently uses a self-signed TLS certificate. Since we are no longer trusting self-signed certs globally in the application to restore our connection with eHX we need to configure trust them when making requests to eHX 
Fixes #2578
For frontend PR’s - include a description (including anything that’s out of scope) for what you want the designers to review
- ex: _“Check out the whitespace on the page, as well as the dropdowns in the form. Here is the corresponding Figma link. You can ignore everything else. Also, the button at the bottom doesn’t work now”_

Trust self-signed certificates when using the eHX FHIR proxy

---

.pre-commit-config.yaml

Some lightweight clean up to our pre-commit configs.
Fixes #
For frontend PR’s - include a description (including anything that’s out of scope) for what you want the designers to review
- ex: _“Check out the whitespace on the page, as well as the dropdowns in the form. Here is the corresponding Figma link. You can ignore everything else. Also, the button at the bottom doesn’t work now”_

Clean up pre-commit configs

---

.github/workflows/cd.yaml

Here is a lightweight CD workflow that will build and push an OCI image of the Query Connector every time we merge to `main`.
Fixes #
For frontend PR’s - include a description (including anything that’s out of scope) for what you want the designers to review
- ex: _“Check out the whitespace on the page, as well as the dropdowns in the form. Here is the corresponding Figma link. You can ignore everything else. Also, the button at the bottom doesn’t work now”_

First draft of CD workflow

---

.github/workflows/cd.yaml

Followup to https://github.com/CDCgov/dibbs-query-connector/pull/28 that gets the build / publish step working.
Fixes the lowercase issue that was breaking the workflow run
Manual run of the workflow [here](https://github.com/CDCgov/dibbs-query-connector/actions/runs/11373266225/job/31639453237) that resulted in a published image [here](https://github.com/CDCgov/dibbs-query-connector/pkgs/container/dibbs-query-connector%2Fquery-connector/versions?filters%5Bversion_type%5D=tagged)

enable image publishing on merges to main

---

query-connector/flyway/sql/V01_06__add_dibbsConceptType.sql

This PR adds a dibbsConceptType column to the `valuesets` table and populates the column with the appropriate data. The new column, `dibbsConceptType` is one of the following values: labs, medications, or conditions, and is based off the ersdConceptType (AKA the `type` column in valuesets). Adding this column and making the data available when queried will allow us to cut down on some of the transformations we complete in order to properly display the data on the CustomQuery page and during query execution. 
Fixes #[phdi #2788](https://app.zenhub.com/workspaces/skylight-dibbs-viper-6480ba23b5a07644e0e46d23/issues/gh/cdcgov/phdi/2788)
This ticket will allow Brandon to continue working on [phdi #2789](https://app.zenhub.com/workspaces/skylight-dibbs-viper-6480ba23b5a07644e0e46d23/issues/gh/c …

Add `dibbsConceptType` to valuesets table

---

query-connector/src/app/constants.ts

This PR adds `Concept`, `ValueSet` and `ValueSetDisplay` data models to our constants. Note: these concepts have not yet been implemented but will be in the follow up ticket [phdi #2789
](https://app.zenhub.com/workspaces/skylight-dibbs-viper-6480ba23b5a07644e0e46d23/issues/gh/cdcgov/phdi/2789) at which point the old data model can be deleted. 
Fixes # [phdi#2760](https://app.zenhub.com/workspaces/skylight-dibbs-viper-6480ba23b5a07644e0e46d23/issues/gh/cdcgov/phdi/2760)
A dataclass for this model has been added to the codebase.

Add internal data model for ValueSet

---

query-connector/flyway/sql/V01_06__add_dibbsConceptType.sql
query-connector/src/app/api/query/route.ts
query-connector/src/app/constants.ts
query-connector/src/app/database-service.ts
query-connector/src/app/format-service.tsx
query-connector/src/app/query-service.ts
query-connector/src/app/query/components/CustomizeQuery.tsx
query-connector/src/app/query/components/SelectQuery.tsx
query-connector/src/app/query/components/customizeQuery/CustomizeQueryAccordionBody.tsx
query-connector/src/app/query/components/customizeQuery/CustomizeQueryAccordionHeader.tsx
query-connector/src/app/query/components/customizeQuery/CustomizeQueryNav.tsx
query-connector/src/app/query/components/customizeQuery/customizeQueryUtils.ts
query-connector/src/app/query/components/selectQuery/queryHooks.ts

This PR refactors our code base to leverage the new value set and concept data models that Marcelle developed as part of her spike work. Refactoring is done throughout the front and back end, fixing how we execute queries as well as display results.
Fixes https://app.zenhub.com/workspaces/skylight-dibbs-viper-6480ba23b5a07644e0e46d23/issues/gh/cdcgov/phdi/2789

Refactor new data model

---

query-connector/src/app/query/components/selectQuery/SelectSavedQuery.tsx

This adds a loading step to the customize query step to prevent from getting ahead of the db load.
I think the only other open questions I had:
* do we want the customize query button unclickable until an actual selection is made? If you click the button, it just takes you to a blank version of the page, which could be a little confusing if the user does think they made a selection.
* is Social Determinants of Health supposed to be broken? Getting this error:
```No results found for query: Social Determinants of Health```
I can open up a ticket to look more closely at it, but I wasn't sure if this was a known bug or if anyone knew offhand why it may now be broken. 
Fixes #47 
For frontend PR’s - …

Adding loading step to customize query selection

---

query-connector/e2e/customize_query.spec.ts
query-connector/e2e/query_workflow.spec.ts
query-connector/playwright.config.ts

This PR adds end to end testing for the customize query workflow. Various facets are tested, including selective valueset filtering, group checking/unchecking, and selecting/deselecting all.
Fixes #https://github.com/CDCgov/dibbs-query-connector/issues/44

Add e2e for customize query

---

query-connector/src/app/query/components/SearchForm.tsx

- Update regex for first name/last name to allow letters, hyphens, apostrophes, spaces, periods, and diacritics.
- Add `title` to `TextInput`s to display validation rule on tooltip message
Fixes #56 
_Patient form field accepts a reasonable (up to the dev to determine what reasonable means!) set of patient names, which would include dashes / apostrophes etc. that might show up in a name_
Allowed characters were chosen based on [USWDS Guidance](https://designsystem.digital.gov/patterns/create-a-user-profile/name/#guidance-2) and [HealthCare.gov](https://www.healthcare.gov/create-account) validation rules/messaging
Some names that should pass validation:
- A'ja Wilson
- Björk Guðmundsdóttir
- Julia Louis-Dreyfus
- Magdalena Carmen Frida Kahlo y Calderón
- St. Joan of Arc
Some names that …

Rework name regex on patient search page

---

query-connector/e2e/customize_query.spec.ts
query-connector/e2e/query_workflow.spec.ts
query-connector/playwright.config.ts
query-connector/src/app/query/SelectQuery.tsx
query-connector/src/app/query/components/selectQuery/SelectSavedQuery.tsx

This PR attempts to cleanup, refactor, and optimize the settings of our end to end tests to minimized flakiness and errors, both locally and on github. Particular attention is paid to reducing the odds that a dev needs to "rerun" the tests in order to force a github pass, as well as to make sure the tests simply work on run when executing locally. With the browser switch already in place, I used the video/trace logs produced by the e2e's (which are absolutely _fantastic_ and get captured for any end to end test that fails at least once) to create a grid-search optimization table to find the best combination of parameters with which to run the tests. This PR introduces the following changes:
- pins the number of retries for each test to 2, since some tests involving public database calls …

Fix all the e2e stuff

---

query-connector/src/app/database-service.ts

This PR modifies the `INSERT` statement of our `InsertValueSet` function to allow for duplicated uniqueIDs to overwrite those of existing entries. Our DB creation process will go through a fair number of duplicate value sets after pulling down the eRSD, so simply overwriting them with the same data will allow the seeding process to proceed more smoothly than error-ing and breaking the transaction.
Fixes #81 
I created a test branch here https://github.com/CDCgov/dibbs-query-connector/tree/test-vs-overwrite that removes database seeding in migrations 2 through 6, and instead adds a button to the landing page that tests a couple cases of inserting valuesets and duplicates into the DB. No errors get thrown and viewing the DB in DBeaver shows all rows correctly entered.

Allow overwriting inserts

---

query-connector/src/app/assets/DIBBS_Custom_ValueSets.json

This ticket adds the custom valuesets we've developed thus far as a JSON object following the `ValueSet` convention we came up with. This will allow us to insert the custom valuesets when creating the database. There's a [follow up ticket](https://linear.app/skylight-cdc/issue/QUE-49/write-script-to-insert-custom-valuesets-into-db) to actually do the insertions. 
Fixes #98 
Note: we do not expect to add any more custom valuesets to this file as we expect users to add their own once we have the query creation work completed.

Create json for custom valuesets using internal valueset schema

---

query-connector/src/app/database-service.ts

This PR introduces a function that verifies that a value set has been successfully inserted into our Postgres DB. Given a FHIR-formatted value set, the function checks that the value set itself has been inserted, all related concepts have been inserted, and all foreign key associations between the two are stored in the relevant tables. This PR also corrects a bug that was introduced when trying to add external IDs, namely that ValueSet IDs were having the version appended twice, which was causing cascading failures when inserting.
Fixes https://github.com/CDCgov/dibbs-query-connector/issues/84
As usual, I've built a test branch with a button that allows you to check the integrity of the insertion and sanity counting code. It's accessible here: …

Vs insertion check

---

query-connector/src/app/queryBuilding/emptyState/EmptyQueriesDisplay.tsx
query-connector/src/db-creation.ts

This lightweight little PR hooks up the button Marcelle created with the DB Creation functions I wrote. Took longer than anticipated to get set up  because of debugging some connectivity issues, though they've since been resolved. The only main thing to note is the `use server` declaration on dbCreation, which forces all the retrieval to occur server-side and keep the API load on the client low.
Since this PR doesn't actually delete the migrations or modify the first one, hitting the button right now isn't needed. The task of actually deleting the migrations will require an overhaul of our end to end tests (which currently rely on seeded data), as well as will make things painful for local devs until or if an extract is prepared that circumvents the need to hit press the button every …

Hook up button to creation script

---

query-connector/src/app/format-service.tsx
query-connector/src/app/tests/unit/format-service.test.tsx

This PR changes the way that we generate the list of phone numbers to search for by replacing non-numeric characters, e.g. `+` and `-`, with their url encoded equivalents. This allows us to query for multiple phone numbers via eHealth Exchange, which eHealth devs recommend. 
Fixes #167 
We may look into more robust URL encoding for other fields, e.g., first names with spaces.

Replace non-numeric characters in phone numbers with url encoding

---

query-connector/README.md
query-connector/docker-compose-dev.yaml

There's two `8080:8080` ports that are causing `npm run dev` to fail due to the bind already existing.
Fixes baby bug.

Changing conflicting ports in docker-compose-dev

---

query-connector/.env.sample
query-connector/docker-compose-dev.yaml

Follow up to #174 - the internal port bind needs to be 8080 since keycloak runs on 8080 by default inside the container. Also updated the `.env.sample` to reflect the new port in the issuer URL.

Make sure keycloak port bind is bound to 8080 inside container

---

query-connector/src/app/api/query/route.ts
query-connector/src/app/database-service.ts
query-connector/src/app/query/components/selectQuery/queryHooks.ts
query-connector/src/app/queryBuilding/buildFromTemplates/page.tsx
query-connector/src/app/queryBuilding/components/ConditionSelection.tsx
query-connector/src/app/queryBuilding/utils.ts
query-connector/src/app/tests/unit/fixtures.ts
query-connector/src/app/tests/unit/utils.test.tsx
query-connector/src/app/utils.tsx

The code that just went in for the new DB tables overloaded a mapping method between @katyasoup and I's PR's that should have been two separate functions. This PR separates them and adds some unit tests to prevent this in the future
Another example of us not having testing infra biting us! Will bring this up at retro
Something else that might have caught this earlier would be more explicitly typing the response from the DB beyond the provided `QueryRow`. **Would love opinions on how we might type our queries more explicitly to tell application code what the shape of data coming back from the DB looks like**

fix translation methods between query pages

---

query-connector/src/app/query/components/CustomizeQuery.tsx
query-connector/src/app/query/designSystem/toast/Toast.tsx
query-connector/src/app/queryBuilding/buildFromTemplates/buildfromTemplate.module.scss
query-connector/src/styles/custom-styles.scss

Follow up to this [slack thread](https://skylight-hq.slack.com/archives/C07PQ078KK2/p1733860243725119?thread_ts=1733499173.941749&cid=C07PQ078KK2)
- Makes body text required / default rendering for toasts
- Tweaks the size of the icons / spacing to be more visually balanced with the smaller text
- Added a min height to the selection form to prevent the UI from blinking on filter
Make sure these toasts look good

tweak toast styles

---

query-connector/src/app/constants.ts

Temporarily changing to HELIOS Meld since Public HAPI is down for the last several days.

Switch from Public HAPI to HELIOS Meld

---

.github/workflows/ecs_terraform.yaml

Currently the terraform workflow is stuck in a loop due to it waiting for user's input to approve the terraform apply. 
- See Github Action [here](https://github.com/CDCgov/dibbs-query-connector/actions/runs/12642805990)
Fixes #
- This PR will add auto-approve so that it no longer waits for user input. 

Fix Terraform workflow

---

query-connector/src/app/assets/dibbs_db_seed_query.json
query-connector/src/app/backend/query-building.ts
query-connector/src/app/query-building.ts
query-connector/src/app/query/designSystem/checkbox/checkbox.module.scss
query-connector/src/app/query/designSystem/drawer/Drawer.tsx
query-connector/src/app/query/designSystem/modal/Modal.tsx
query-connector/src/app/queryBuilding/page.tsx
query-connector/src/app/queryBuilding/querySelection/QueryLibrary.tsx
query-connector/src/app/queryBuilding/utils.ts
query-connector/src/app/tests/assets/aphlCategoryMapping.json
query-connector/src/app/tests/unit/fixtures.ts
query-connector/src/app/tests/unit/utils.test.tsx
query-connector/src/app/utils.ts
query-connector/src/app/utils/valueSetTranslation.test.ts
query-connector/src/app/utils/valueSetTranslation.ts
query-connector/src/styles/design-system.scss

Part one of the query building effort to slim down the final PR. Changes include
- We decided to store the JSON in the `query_data` and `conditions_list` columns of the query table by condition ID rather than condition name like we had it previously. Updated the fixtures / unit tests / seed file and one place in the frontend UI accordingly
- Introduce the code to do the query upserts, to be consumed in the upcoming PR
- Added some UI gating / updating: should be a no-op for now
Part one of #255

query building write functionality pt 1

---

query-connector/e2e/alternate_queries.spec.ts
query-connector/e2e/customize_query.spec.ts
query-connector/e2e/load.spec.ts
query-connector/e2e/query_workflow.spec.ts
query-connector/src/app/page.module.scss
query-connector/src/app/page.tsx

As it says on the tin, per a convo with Michelle. Writing a ticket was more work than changing it, so went ahead and did it.
Before
After
- Remove the extra copy about sample data / change the CTA copy as well

move the landing page call-to-action above the fold

---

.github/workflows/ecs_terraform.yaml
.github/workflows/terraform_plan.yaml
terraform/implementation/ecs/demo.tfvars
terraform/implementation/ecs/main.tf

- Modified ecs_workflow.yaml to be dependent on cd.yaml so that the new image can build before a new deployment is triggered
- Deployed demo environment on ECS
- Moving forward the Terraform deployment will not be automatic. Developer will have to run Github action named `Terraform Plan & Terraform Apply`
-- After PR is merged to `main` navigate to Actions select the branch which should be `main` and `environment` the PR merged is intended for:
Fixes #

Demo workspace depolyment

---

query-connector/src/app/query/components/header/header.tsx

Fixes homepage redirect as discussed in 1/13 planning. To be revisited once auth is more fully implemented
- Comments out the sign in button on the homepage to reduce confusion / not expose something that doesn't work
- Adds the FHIR server configuration and query building paths to the gear for everyone.
- Will merge after Nick's work goes in so the FHIR server path points to a valid page (happy to ping Shanice as well)

adjust homepage and in-app nav

---

query-connector/src/app/assets/DIBBs_Query_Connector_API.postman_collection.json

Updates the `base_url` in the Postman collection to use `demo.queryconnector.dev` instead of `dibbs.cloud` for the Connectathon
Fixes #

Update base_url for Postman collection to demo.queryconnector.dev

---

query-connector/src/app/queryBuilding/buildFromTemplates/BuildFromTemplates.tsx
query-connector/src/app/queryBuilding/components/SelectionViewAccordionHeader.tsx

Making the width of the input longer. 
Current:
New:
Width updated from  `maxw-mobile` to `width-card-lg` with the out-the-box uswds widths. We can do a custom width, but figured it made sense to stick with the out-the-box where possible.
Fixes #280

Updating input field length on Custom Query page

---

query-connector/src/app/api/test-fhir-connection/route.ts
query-connector/src/app/database-service.ts
query-connector/src/app/fhir-servers/page.tsx
query-connector/src/app/query-service.ts
query-connector/src/styles/custom-styles.scss

Add a drop down to the FHIR server config modal for "auth method" with none and basic auth as options. If basic auth is selected, show a text field for a bearer token.
Had to disable cert validation to get "Test connection" to work against the iz gateway demo. We should definitely not keep that in production.
https://linear.app/skylight-cdc/issue/QUE-137/add-basic-auth-to-fhir-server-configuration

Add basic auth to FHIR server configuration

---

query-connector/e2e/query_workflow.spec.ts
query-connector/src/app/constants.ts
query-connector/src/app/query-service.ts

The PR also includes a bit of cleanup on constants that are no longer used (patientOptions and patientType). To dedupe resources added to the `QueryResponse` and then displayed to users, I modified `processFhirResponse` and `parseFhirSearch`.  
The modifications to `processFhirResponse` dedupe resources returned in a given query for a resource type. That is, when we query for Observations using a list of codes, these changes will only add Observations with unique IDs for that query. 
The modifications to `parseFhirSearch` dedupe resources across a whole query, e.g. "My STLT's Chlamydia Query". This is important if we end up pulling back resources of the same type (e.g., Observations) from separately executed queries because the resources would not be deduped by `processFhirResponse` …

Dedupe FHIR Resources Parsed by Queries

---

query-connector/src/app/constants.ts
query-connector/src/app/query-service.ts

This PR switches all instances of the DIBBs version of `FhirResource` to the one from `fhir/r4` for more robust typing and future proofing for additional resource queries.
Fixes #310
I thought we were using the DIBBs version in a lot more places and thought this would be a bigger PR 😆

Use `FhirResource` from `fhir/r4`, not a DIBBS definition

---

query-connector/e2e/customize_query.spec.ts
query-connector/e2e/query_workflow.spec.ts
query-connector/src/app/shared/format-service.tsx
query-connector/src/app/tests/assets/GoldenSickPatient.json
query-connector/src/app/tests/unit/format-service.test.tsx

This PR updates the formatters for MRN and Identifiers more broadly to include `assigner`, where applicable. That is, if you have an MRN with an assigner, e.g., a hospital name, it will now be displayed in the Patient Search results page and the final results page. Previously, MRN would just display the number such as `1234` but now it will display `St. Worrywart’s Medical Center: 1234` under MRN in the patient search result page and `Medical Record Number: St. Worrywart’s Medical Center: 1234` under Patient Identifiers on the results page.
I also updated Hyper Unlucky's data to include an assigner and a Driver's License to show what happens when you have multiple identifiers.
Fixes #296 
I intentionally did not include a new search field for the Assigner. We have another ticket in the …

Update MRN and Identifier Formatting to include Assigner

---

query-connector/src/app/backend/user-management.ts

This initializes new users as a standard user role in the user-management table.
One question/concern I had; I had initialize explored creating a `qcRoleSuperAdmin`, `qcRoleAdmin`, and `qcRoleStandardUser` in Keycloak. My initial code included initializing these roles, pushing these roles back into Keycloak with a new master-realm, and having the create/update functions also push those roles back into Keycloak. 
However, the more I thought about it, I was not entirely sure if we wanted or needed to take this step, given that I would think we would a service-agnostic approach to restricting what pages/services a user had access to. Thoughts?
This new function should be the only one you need to pull into the new page to update user roles. As of now, the only user in the `user-management` …

Initializing users, function to update qc_role

---

query-connector/docker-compose-dev.yaml
query-connector/docker-compose.yaml

Removing arguments from docker-compose.yml that stop keycloak from starting up:
```
keycloak-1         | Appending additional Java properties to JAVA_OPTS
keycloak-1         | Unrecognized VM option 'UseSVE=0'
keycloak-1         | Error: Could not create the Java Virtual Machine.
keycloak-1         | Error: A fatal exception has occurred. Program will exit.
keycloak-1 exited with code 0
```
I _think_ the `select-realm.sh` assignment of `JAVA_OPTS_APPEND` if m4 should be sufficient, but I'm not entirely sure.
Fixes #

Remove JAVA_OPTS_APPEND from docker compose

---

query-connector/src/app/ui/components/page/page.tsx
query-connector/src/app/ui/designSystem/drawer/Drawer.tsx
query-connector/src/app/ui/designSystem/drawer/drawer.module.scss

noticed a couple issues in the query building flow during demo prep
- Tweaked a toast container option configuration so that any option overrides work correctly
- Gave the drawer a max width to match the design intention on wider screens
- Tweaking a padding property on the drawer title in cases where we don't have subtitles
Drawer width:
Before
After

query building tweaks

---

query-connector/src/auth.ts

Noticed that the debug logs for Next Auth will log out session information that has PII  into the system logs. Turning them off before we accidentally ship something that will cause an incident.
Happy also to pull this into an env var if we want, but haven't heard that we've really used this so electing to be more conservative in this case

turn off next auth debug mode

---

query-connector/jest.config.js
query-connector/package-lock.json
query-connector/src/app/backend/user-management.ts
query-connector/src/app/tests/integration/user_management.test.ts
query-connector/src/app/utils/auth.ts

This adds the initial work to get usergroup data, create new entries, update entries, and delete entries. This leverages the existing `UserGroup` work.
Future tickets will address creating/updating/deleting the connective tables for the respective userGroup -> users and userGroup -> queries. 
Per the ERD write-up, it sounds as though admins will also need to have permission to do update user groups (https://docs.google.com/document/d/1b319fzLJ1vJFfdyokelbBR7GyiSpQBe_dBICBseVRRU/edit?tab=t.0), so I just added a new function to do that, as well. 
Fixes #371 

Initialize UserGroup insert/update/delete work

---

.github/pull_request_template.md
query-connector/.gitignore
query-connector/package-lock.json
query-connector/package.json
query-connector/src/app/(pages)/query/components/PatientSearchResults.tsx
query-connector/src/app/(pages)/query/components/ResultsView.tsx
query-connector/src/app/(pages)/query/components/SelectQuery.tsx
query-connector/src/app/(pages)/query/components/patientSearchResults/NoPatientsFound.tsx
query-connector/src/app/(pages)/query/components/patientSearchResults/PatientSearchResultsTable.tsx
query-connector/src/app/(pages)/query/components/resultsView/ResultsViewAccordionBody.tsx
query-connector/src/app/(pages)/query/components/resultsView/ResultsViewSideNav.tsx
query-connector/src/app/(pages)/query/components/resultsView/ResultsViewTable.tsx
query-connector/src/app/(pages)/query/components/resultsView/resultsView.module.scss
query-connector/src/app/(pages)/query/components/searchForm/SearchForm.tsx
query-connector/src/app/(pages)/query/page.tsx
query-connector/src/app/(pages)/queryBuilding/querySelection/QueryLibrary.tsx
query-connector/src/app/(pages)/queryBuilding/querySelection/utils.tsx
query-connector/src/app/(pages)/userManagement/page.tsx
query-connector/src/app/ui/components/page/page.tsx
query-connector/src/app/ui/designSystem/table/Table.tsx

Adds loading skeletons to the query execution flow in accordance to [best-practice guidance on loading states](https://www.nngroup.com/articles/skeleton-screens/).
https://github.com/user-attachments/assets/d97373b9-ad25-4a0b-b10f-afeab8087c8b
Elected not to add the loading UI to the query building flow since the page transitions are under 2 seconds and [guidance suggests skeletons aren't necessary in those cases](https://www.nngroup.com/articles/skeleton-screens/#:~:text=If%20a%20page%20takes%20less%20than%201%20second%20to%20load%2C%20skeleton%20screens%20or%20spinners%20aren%E2%80%99t%20necessary%2C). The execution flow has a few steps where the wait time is a bit longer (ie the query out to FHIR servers), so decided to add those accordingly.
Fixes #51

add loading skeletons to query execution flow

---

query-connector/src/app/backend/usergroup-management.ts
query-connector/src/app/models/entities/user-management.ts
query-connector/src/app/tests/integration/usergroup-management.test.ts
query-connector/src/app/utils/auth.test.ts

This adds the functions for adding/deleting queries from a user group. It follows the same structure as the work to add/remove Users. Also adds some additional tests.
Fixes #374 
Having some trouble addressing the issues raised in the testing suite; I added tests for admin and superadmin tests, thinking that that should suppress/remove the need for us to constantly check for each unauthorized test. Not sure if there's a better way to do this, or if it's just easier to add a test for each of these functions.
I'm not sure if that's what it's all treating the get status functions as untested? I wish there was a little more guidance as to what was wrong here 😕 .

Initializing Query drawer backend for User group work

---

query-connector/docker-compose-dev.yaml
query-connector/src/app/shared/constants.ts

Hotfix for Aidbox port conflict issue until we can put together the local seeding script.
Temporarily
- Switches default back to Public HAPI
- Adds Aidbox to the dump file (without a functioning URL, so the Aidbox dropdown option won't work) as well as updates the dumpfile with the new user management tables
- The seeding script should replace this once it's working properly 
- Swaps the port setup in local dev to 8082 to not conflict with Public HAPI / Keycloak

Aidbox local hotfix

---

query-connector/src/app/(pages)/query/page.tsx
query-connector/src/app/shared/DataProvider.tsx
query-connector/src/auth.ts

One of the gaps identified in our current session implementation was that updates to a user's role were not propagated to the frontend pages. This is mainly due to the SPA nature of the query connector app in which the session object is retrieved from the server only on first load and then stored in the browser memory. All other access after that point are done towards the session copy in memory so updates to a user were not available by default.
This PR introduces code to keep the session object in the browser in sync with the server and it uses the `SessionProvider -> refetchInterval` feature available in `next-auth/react`. The library will make an HTTP request to the server in the interval defined (in our case it has been set to 15 mins) and will refresh the session object in the …

Setup session refresh in session provider

---

query-connector/e2e/query_building.spec.ts
query-connector/playwright.config.ts
query-connector/src/app/(pages)/queryBuilding/buildFromTemplates/BuildFromTemplates.test.tsx
query-connector/src/app/(pages)/queryBuilding/components/ValueSetSelection.tsx
query-connector/src/app/(pages)/queryBuilding/querySelection/QueryLibrary.tsx

Addresses the extra page issue logged [here](https://linear.app/skylight-cdc/issue/QUE-136/editing-a-query-should-take-you-to-the-query-not-the-checklist) and removes the intermediary step before actually editing a query in a user's "my queries" page when logged in to QC. 
Fixes #136

fix for QUE-136 fix edit queries

---

query-connector/package-lock.json
query-connector/src/app/(pages)/.well-known/jwks.json/route.ts
query-connector/src/app/api/test-fhir-connection/route.ts
query-connector/src/app/backend/dbServices/fhir-servers.ts
query-connector/src/app/backend/dbServices/queryBuilding/lib.ts
query-connector/src/app/backend/dbServices/smartOnFhir/lib.ts
query-connector/src/app/backend/query-building.ts
query-connector/src/app/shared/fhirClient.ts
query-connector/src/app/shared/query-service.ts

Part two of SMART on FHIR implementation that implements backend functionality. 
Follow up to #455 and part two of [QUE-211](https://linear.app/skylight-cdc/issue/QUE-211/implement-smart-on-fhir)
This includes the backend code for asymmetric key SMART on FHIR auth working as described in:
- https://build.fhir.org/ig/HL7/smart-app-launch/backend-services.html
- https://build.fhir.org/ig/HL7/smart-app-launch/client-confidential-asymmetric.html#authenticating-to-the-token-endpoint
- https://docs.aidbox.app/modules/security-and-access-control/smart-on-fhir/smart-client-authentication/smart-asymmetric-private-key-jwt-authentication
A forthcoming PR will propagate this new code into the frontend FHIR server modal
* Refactored the JWKS generation process to [dynamically generate or load RSA keys …

SMART on FHIR pt 2 - backend changes

---

query-connector/src/app/(pages)/queryBuilding/buildFromTemplates/ConditionColumnDisplay.tsx
query-connector/src/app/(pages)/queryBuilding/components/ValueSetSelection.tsx
query-connector/src/app/(pages)/queryBuilding/utils.ts

Adds commonly-used abbreviations for category and condition names. 
For categories, this is done by adding `formatCategoryDisplay` to allow us to extend the names beyond those received by APHL with a new mapping.
For conditions, this is done by extending `formatDiseaseDisplay` to make specific changes based on need. Right now, this is just HIV.
This also uncovered a baby bug with our search, which was being done on the raw condition name. Many of the condition names in our data have a `(disorder)` appended to them, which we visually removed with `formatDiseaseDisplay`. However, when someone still searched "disorder", many results were still hit.
Fixes #479 

Adding help text to category and condition data

---

query-connector/.env.sample
query-connector/docker-compose-dev.yaml
query-connector/docker-compose-e2e.yaml
query-connector/docker-compose-integration.yaml

M3 still has an issue where a fatal error will occur with `JAVA_TOOL_OPTIONS=-XX:UseSVE=0`. There was also an issue with my machine building the edge version of the image, but did not have any with stable. So I rolled back the images to stable for...stability.
The main update to confirm for M1 and M4 users is that adding this: `JAVA_TOOL_OPTIONS=-XX:UseSVE=0` to your `.env` file should be sufficient to still start up `npm run dev` with Aidbox available.
Please let me know if this works.
Fixes #

Moving from edge Aidboxone to stable Aidboxone

---

query-connector/src/app/auditLogs/decorator.ts
query-connector/src/app/auditLogs/lib.ts
query-connector/src/app/tests/integration/audit-logging.test.ts

This adds a hashing function to the audit log table that conducts an update of the audit log role.
The other option to do this would be to INSERT the datetime, as opposed to relying on postgres' NOW() function. We need the datetime for the checksum, and I was concerned that the slight differences in using a datetime computed by the function and one by postgres could lead to small deltas in time. It might be okay if there's a millisecond difference, though...not sure.
Fixes #476 

Adding audit log hash update

---

query-connector/src/app/(pages)/userManagement/components/userModal/userModal.tsx
query-connector/src/app/ui/components/sessionTimeout/sessionTimeout.tsx
query-connector/src/app/ui/designSystem/modal/Modal.tsx
query-connector/src/app/ui/designSystem/modal/deleteModal.tsx
query-connector/src/app/ui/styles/custom-styles.scss

Modals had slightly different styling for each different place they appeared in the app; this PR unifies the font/color/layout of the Modal component . 
Fixes #470 
OLD modal styles are on the left, NEW modal styles are on the right:
**FHIR Server modals**
- [Both] Updated font; updated close button placement
- [Add server] Updated Cancel button placement to align with other modals:
**Delete Query & Session Timeout modals**
- [Delete query] Updated Cancel, Delete button styling and placement; updated close button placement
- [Session timeout] Swapped button placement to align with other modals
**User Management modals**
- [All] Updated font and rounded corners:

Streamline modal styles

---

.github/workflows/ci.yaml
.gitignore
query-connector/README.md
query-connector/docker-compose-e2e.yaml
query-connector/e2e/smart_on_fhir.spec.ts
query-connector/setup-scripts/e2e_tests.sh
query-connector/setup-scripts/e2e_tests_local.sh
query-connector/setup-scripts/unit_and_integration_tests.sh
query-connector/src/app/backend/dbServices/smartOnFhir/lib.ts

When looking into fixing the e2e's noticed some areas of improvement for how we're seeding env variables in our e2e scripts. 
- All Dockerized versions of the e2e's (in CI and local run using `npm run test:playwright`) have the e2e's seeded within the `.e2e_tests.sh` script rather than relying on the `ci.yaml` file and the dev's local .env file respectively
- We do have one secret (the Aidbox license) in the e2e run chain, so added some code to look for that value in the `.env` and then seed that accordingly 
- The Playwright UI command has its e2e var's seeded in the `.e2e_tests_local.sh` script
- All e2e tests now generate / teardown their own `.env.e2e` files so as to separate concerns with any floating .env files
- Added a note about the SMART on FHIR e2e not working for local UI mode …

modularize e2e env var seeding

---

query-connector/next-env.d.ts
query-connector/src/app/(pages)/fhirServers/page.tsx
query-connector/src/app/backend/dbServices/audit-logs.ts
query-connector/src/app/backend/dbServices/db-service.ts
query-connector/src/app/backend/dbServices/fhir-servers.ts
query-connector/src/app/backend/dbServices/util.ts
query-connector/src/app/models/entities/fhir-servers.ts
query-connector/src/app/shared/DataProvider.tsx
query-connector/src/app/shared/fhirClient.ts
query-connector/src/app/shared/query-service.ts
query-connector/src/app/tests/integration/fhir-servers.test.ts
query-connector/src/app/tests/integration/user-management.test.ts
query-connector/src/app/ui/components/withAuth/WithAuth.tsx
query-connector/src/app/ui/designSystem/SiteAlert.tsx

Refactors the `FhirServersService` to return read queries using camel casing. Picked up some other misc organizational improvements as well
Part of #515 
- Split out the functionality within the FhirServers class to be protected so that internal service code could call it while external facing code is decorated with permissions checks
- Moved the FHIR client preparation code into the services class to take advantage of the above

refactor fhirServers service to use camel case decorator

---

src/app/(pages)/query/components/searchForm/SearchForm.tsx
src/app/backend/dbServices/fhir-servers.ts
src/app/shared/fhirClient.ts
terraform/modules/oidc/_data.tf

PR that adds a fallback FHIR server in the event that the hard coded Aidbox server isn't defined, as well as some retry logic for FHIR client setup if there's a potentially cache miss.
Screen recording below shows the state directly before (where Public HAPI becomes the fallback) and after Aidbox was seeded (where the default updates to use Aidbox)
https://github.com/user-attachments/assets/68400174-80d3-45a4-b53d-358db621fe8b
A result of the discussion [here](https://skylight-hq.slack.com/archives/C05BEG226RZ/p1746045646886299)

refactor fhir server setup interface

---

flyway/sql/V13_01__add_default_fhir_server.sql
setup-scripts/seed_aidbox.sh
src/app/(pages)/fhirServers/page.tsx
src/app/(pages)/query/components/searchForm/SearchForm.tsx
src/app/(pages)/query/page.tsx
src/app/backend/dbServices/fhir-servers.ts
src/app/backend/dbServices/util.ts
src/app/models/entities/fhir-servers.ts
src/app/shared/constants.ts
src/app/shared/fhirClient.ts
src/app/tests/integration/fhir-servers.test.ts

Adds the ability to choose one FHIR server as the default. 
Fixes #535 
https://linear.app/skylight-cdc/issue/QUE-248/make-default-fhir-server-configurable
This pull request introduces a "default server" feature for FHIR servers, allowing one server to be designated as the default. Key changes include database schema updates, backend service modifications, and frontend adjustments to support this new functionality.
* Added a `default_server` column to the `fhir_servers` table and enforced a unique constraint to ensure only one server can be marked as default at a time. (`flyway/sql/V13_01__add_default_fhir_server.sql`)
* Updated the `FhirServerConfigService` class to handle the `defaultServer` property, including sorting servers to prioritize the default server and modifying SQL queries …

Add ability to specify default FHIR server

---

terraform/implementation/ecs/main.tf

#530 changed the way we tagged our docker images - this will fix our deploys to actually pull the latest until we start properly assigning version numbers

Switch image tag pulled by Terraform to "latest"

---

src/app/(pages)/codeLibrary/CodeLibrary.test.tsx
src/app/(pages)/codeLibrary/__snapshots__/CodeLibrary.test.tsx.snap
src/app/(pages)/codeLibrary/page.tsx
src/app/(pages)/queryBuilding/buildFromTemplates/BuildFromTemplates.tsx
src/app/(pages)/queryBuilding/buildFromTemplates/conditionTemplateSelection.module.scss
src/app/(pages)/queryBuilding/components/ConditionSelection.tsx
src/app/(pages)/queryBuilding/components/ValueSetSelection.tsx
src/app/(pages)/queryBuilding/page.tsx
src/app/(pages)/queryBuilding/querySelection/utils.tsx
src/app/backend/query-building/useSaveQueryAndRedirect.ts

Updates the navigation display text for custom codes pages:
- When navigating to `/codeLibrary` from the gear menu: 
- no back link appears
- When navigating to `/codeLibrary` via the "start from scratch" link:
- Back link reads "Back to templates"
- Clicking back link loads the `/queryBuilding` page with `buildStep` set to "condition"
- Query name is persisted
- When navigating to `/codeLibrary` via the "Add codes from library" button:
- Back link reads "Back to Create query"
- Clicking back link loads the `/queryBuilding` page with `buildStep` set to "valuesets"
- Query name is persisted
**NOTE**: "select" mode for the `codeLibrary` page is not included in this PR; the page will be blank with just the back link.  _Query data is also currently not persisted on backnav_. This …

String custom codes pages together

---

e2e/query_building.spec.ts
e2e/query_editing.spec.ts
src/app/(pages)/query/components/selectQuery/NoQueriesDisplay.tsx
src/app/(pages)/query/components/selectQuery/QueryRedirectDisplay.tsx
src/app/(pages)/queryBuilding/__snapshots__/page.test.tsx.snap
src/app/(pages)/queryBuilding/page.test.tsx
src/app/(pages)/queryBuilding/querySelection/EmptyQueriesDisplay.tsx
src/app/(pages)/queryBuilding/querySelection/QueryRepository.tsx
src/app/(pages)/queryBuilding/querySelection/QuerySelection.tsx
src/app/shared/constants.ts
src/app/shared/page-routes.ts

Renames the Query library page and all references to `Query repository`, to more clearly distinguish it from `Code library`. 
Fixes #621 

Rename Query Library to Query Repository

---

src/app/(pages)/codeLibrary/__snapshots__/CodeLibrary.test.tsx.snap
src/app/(pages)/codeLibrary/codeLibrary.module.scss
src/app/(pages)/codeLibrary/page.tsx

Noticed while reviewing the Next upgrade PR that the dropdown filter on /codeLibrary was still sometimes getting stuck in the disabled state. Also the bottom margin of the PaginationContainer was too high, and the filter button was misaligned with its icon.
Before:
After:

Tweak CodeLibrary styles

---

src/app/(pages)/fhirServers/page.tsx

When testing a connection to a FHIR server, if there is an error, the error message persists when you close the modal and open a different FHIR server. This is because `resetModalState()` was getting called when the modal was closed via one of its buttons, but not when closing via the `X` in the top right, clicking outside the modal, or hitting the escape key.
Fixes #651 

Clear error message when closing FHIR server config modal

---

terraform/implementation/ecs/main.tf

We need to set the correct env var in our deployed environment for selecting the auth provider

Fix auth provider env var

---

terraform/implementation/ecs/_variable.tf

Deploys are currently broken because our dev RDS instance got upgraded (perhaps by @rin-skylight? perhaps automatically? not sure) from 16.3 to 16.8, but Terraform has it pinned to 16.3. This should fix it!

Upgrade RDS engine version to 16.8 in dev

---

src/app/(pages)/codeLibrary/__snapshots__/CodeLibrary.test.tsx.snap
src/app/(pages)/codeLibrary/codeLibrary.module.scss
src/app/(pages)/codeLibrary/page.tsx

Noticed some funky hover states on the buttons of the editing/deleting custom valuesets. I think it's fixed just by relying on our secondary button styling.
https://github.com/user-attachments/assets/ee5869d9-9cea-4881-ab0a-daf63e915697
https://github.com/user-attachments/assets/75593100-f440-47c7-9c91-e369cbcd1c96
Fixes #

Fixing Code Library button hover state
